"""Exceptions for evohomesecurity API library."""

class ApiException(Exception): ...


class AuthException(ApiException): ...


class CmdException(ApiException): ...


class ParseException(ApiException): ...
